### ISSUE TITLE
Adjust title when duplicating workspace

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/mise#133] opened 2021-05-14 22:27 UTC
When the user uses the Duplicate workspace action, the duplicated workspace is created using the same title as the source workspace. This is potentially a bit confusing for the user, who then can have two workspaces with the same name:

<img width="623" alt="Screen Shot 2021-05-14 at 3 17 16 PM" src="https://user-images.githubusercontent.com/101482/118336962-9cf92f80-b4c7-11eb-89bc-b451a884d230.png">

---

I'm not suggesting we prohibit duplicate workspace names, but I wonder if we can automatically prepend "Duplicate of" to the title of the duplicated workspace when creating it? This would:

1. Make it more clear to the user which is the duplicated workspace (it is clear if the user pays attention to the last edit info, but (separate issue) I'm wondering whether we should remove that from the workspace card)
2. Make it more likely, perhaps, that the user edits the now annoying title to make it more meaningful/distinguishable from the original

So the same duplicate action as shown in the first screenshot above would instead look like this after the duplicate action completes:

<img width="623" alt="Screen Shot 2021-05-14 at 3 19 55 PM" src="https://user-images.githubusercontent.com/101482/118337409-98814680-b4c8-11eb-8b02-c5966104318f.png">

**Comment by cbeer** [comment] 2021-05-14 22:30
"Duplicate of duplicate of duplicate of project 1 final draft final this is the one" :trollface:

**Comment by ggeisler** [comment] 2021-05-14 22:57
Ha, yeah, I pretty much had that in my Google Drive yesterday when I made a bunch of copies of the stakeholder feedback document to split it into multiple documents. Except it was "Copy of Copy of Copy of Copy of Stakeholder feedback"

**Closed** 2021-05-18 14:39 UTC
